apiVersion: v1
version: 1.1.4
appVersion: 1.9.0
name: app-with-chart
description: App with Chart Helm chart for Kubernetes
home: https://github.com/satr/app-with-chart
maintainers:
- email: satr.github.io@gmail.com
  name: satr
sources:
- https://github.com/satr/app-with-chart
kubeVersion: ">=1.19.0-0"
