# Default values for app.

clusterFQDN: xx

image:
  repository: xx
  tag: xx
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 120Mi
  requests:
    cpu: 50m
    memory: 109Mi
